sudo: required

language: python

before_install:
- sudo apt-get update -q
- sudo apt-get install -y curl
- curl -o bootstrap-salt.sh -L https://bootstrap.saltstack.com
- sudo sh bootstrap-salt.sh git develop

install:
- salt-call --help
