sudo: required

language: python

before_install:
- python -c 'import urllib; print urllib.urlopen("https://bootstrap.saltstack.com").read()' > bootstrap-salt.sh
- sudo sh bootstrap-salt.sh git develop

install:
- salt-call --help
